# Kubernetes Deployment for Visey Recommender with Load Balancing
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visey-recommender
  namespace: visey
  labels:
    app: visey-recommender
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: visey-recommender
  template:
    metadata:
      labels:
        app: visey-recommender
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: visey-recommender
        image: visey-recommender:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: WP_BASE_URL
          valueFrom:
            secretKeyRef:
              name: visey-secrets
              key: wp-base-url
        - name: WP_AUTH_TYPE
          valueFrom:
            configMapKeyRef:
              name: visey-config
              key: wp-auth-type
        - name: WP_USERNAME
          valueFrom:
            secretKeyRef:
              name: visey-secrets
              key: wp-username
        - name: WP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: visey-secrets
              key: wp-password
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-data
          mountPath: /app/data
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: visey-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: visey-recommender-service
  namespace: visey
  labels:
    app: visey-recommender
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: visey-recommender

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visey-recommender-ingress
  namespace: visey
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    # Enable caching for recommendations
    nginx.ingress.kubernetes.io/server-snippet: |
      location /recommend {
        proxy_cache visey_cache;
        proxy_cache_key "$scheme$request_method$host$request_uri$arg_user_id";
        proxy_cache_valid 200 5m;
        proxy_cache_use_stale error timeout updating;
        add_header X-Cache-Status $upstream_cache_status;
      }
spec:
  tls:
  - hosts:
    - visey-recommender.com
    secretName: visey-tls-secret
  rules:
  - host: visey-recommender.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: visey-recommender-service
            port:
              number: 8000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: visey-config
  namespace: visey
data:
  wp-auth-type: "basic"
  wp-sync-interval: "30"
  wp-cache-fallback: "true"
  wp-rate-limit: "60"
  wp-batch-size: "100"

---
apiVersion: v1
kind: Secret
metadata:
  name: visey-secrets
  namespace: visey
type: Opaque
data:
  wp-base-url: # base64 encoded WordPress URL
  wp-username: # base64 encoded username
  wp-password: # base64 encoded password

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: visey-pvc
  namespace: visey
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: visey-recommender-pdb
  namespace: visey
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: visey-recommender

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visey-recommender-hpa
  namespace: visey
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visey-recommender
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60