name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
    
    - name: Create Docker image
      run: |
        docker build -t visey-recommender:${{ github.event.release.tag_name }} .
        docker tag visey-recommender:${{ github.event.release.tag_name }} visey-recommender:latest
    
    - name: Deploy to production
      run: |
        echo "Deploying version ${{ github.event.release.tag_name }} to production..."
        # Add production deployment commands here